import { createEvent } from 'effector';
import { IInfoImg } from '../interfaces/items';

export const setImages = createEvent<IInfoImg[]>();
export const setCurrentCropImage = createEvent<IInfoImg[]>();
export const setLengthKitsImages = createEvent<number>();
export const setKitImages = createEvent<any>();
export const nextKitImages = createEvent();
export const previousKitImages = createEvent();
export const setCurrentIdx = createEvent<number>();
export const activeModal = createEvent();
export const disableModal = createEvent();
export const nextNumberImg = createEvent();
export const setColor = createEvent<any>();
export const setQuality = createEvent<any>();
export const setIsCroppedImages = createEvent<boolean>();
export const cancelImg = createEvent<number>();
export const cancelCropImg = createEvent<number>();
export const setCancelCropImg = createEvent<any>();
export const setKitsImages = createEvent<any>();
export const setTypeCrop = createEvent<string>();
export const setImagesFromLocalStorage = createEvent<any>();
export const setSettingForKitsImages = createEvent<any>();
export const setkitsImages = createEvent<any>();
export const setPointImg = createEvent<any>();
export const setPointImgInKitImages = createEvent<any>();
export const addKitImageSettings = createEvent<any>();
export const setKitsImagesSettings = createEvent<any>();
export const setIsLocalDataLoaded = createEvent<boolean>();

export const setAspect = createEvent<any>();
export const cancelAspect = createEvent<any>();
export const setCropDataPx = createEvent<any>();
export const setCropDataPercent = createEvent<any>();
export const setCropperRef = createEvent<any>();
